name: processing_compiler
description: A processing idea project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.4
  webview_flutter: 3.0.4
  styled_widget: 0.4.0+3
  get: 4.6.3
  hive_flutter: 1.1.0
  flex_color_scheme: 5.0.1
  flutter_slidable: 1.1.0
  flutter_svg:
  timeago: 3.2.2
  url_launcher: 6.1.2
  shared_preferences: 2.0.15
  google_fonts: 3.0.0
  share_plus: 4.0.4
  flutter_highlight: 0.7.0
  flutter_html: 3.0.0-alpha.3
  flutter_staggered_grid_view: 0.6.0
  flutter_syntax_view: 4.0.0
  cached_network_image: 3.2.1
  umeng_common_sdk: 1.2.4
  dart_code_metrics: 4.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0
  hive_generator: 1.1.3
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  build_runner: 2.1.5
  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: 0.9.2
  flutter_native_splash: 1.3.2
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/
