/// @author u
/// @date 2020/6/12.

final List<Language> gSupportLanguages = [
  Language('English', '英语', 'en'),
  Language('简体中文', '简体中文', 'zh'),
  Language('繁體中文', '繁体中文', 'cht'),
  Language('日本語', '日语', 'jp'),
  Language('Español', '西班牙语', 'spa'),
  Language('Français', '法语', 'fra'),
  Language('Deutsch', '德语', 'de'),
  Language('Italiano', '意大利语', 'it'),
  Language('한국어 공부 해요.', '韩语', 'kor'),
];

class Language {
  final String language;
  final String desc;
  final String code;

  Language(this.language, this.desc, this.code);
}

Map<String, Map<String, String>> gAllSupportLanguage = {
  "en": {
    "app_share": "Processing or p5. js or Py by Compiler",
    "about": "Contact me",
    "feature": "Knowledge points",
    "search": "Quick check",
    "search_result_empty": "No relevant information was found. Please try other keywords",
    "name": "Name",
    "fields": "Field",
    "example": "Example",
    "error_desc": "If the translation content is incorrect or the page is abnormal, please contact me in time. Thank you for your support!",
    "code": "Source code",
    "parameters": "Parameter",
    "constructors": "Construction method",
    "methods": "Member method",
    "syntax": "Grammar",
    "name_function": "Function name",
    "name_class": "Class name",
    "description": "Describe",
    "code_examples": "Code example",
    "share": "Share",
    "feedback": "Feedback on relevant problems of processing compiler",
    "like_me": "Encourage me",
    "ok": "Determine",
    "recommend": "Recommend friends",
    "wechat": "WeChat",
    "rename": "Rename",
    "more": "More",
    "email": "Mailbox",
    "Processing中文论坛": "Processing Chinese Forum",
    "about_how": "How can I be contacted",
    "light_mode": "Light mode",
    "dark_mode": "Dark Mode ",
    "system_mode": "Follow system",
    "reset": "Restore default mode",
    "theme": "Theme style",
    "email_error":
        "Failed to start the mailbox program. Please check whether the mailbox program is installed. If you have more questions, please go to the application market for feedback",
    "qq_error": "Failed to start the QQ program. Please check whether the QQ program is installed. If you have more questions, please go to the application market for feedback",
    "theme_setting": "Set theme style",
    "app_name": "Processing",
    "create_project": "Create a new project",
    "create_processing": "New processing project",
    "create_p5": "New P5 JS project",
    "create_python": "Create a new processing Py project",
    "editor_setting": "Editor Settings ",
    "setting": "Set up",
    "show_code_line_number": "Display code line number",
    "setting_code_font_size": "Set code font size",
    "setting_code_full_screen": "Whether it is full screen",
    "code_theme": "Editor style",
    "empty_pro": "Start your creative programming!",
    "loading": "Loading",
    "slide_setting_font_size": "Slide your finger to set the font size",
    "project": "Project",
    "reference": "Reference resources",
    "createTimeDesc": "Created on:",
    "china_bbs": "Processing Chinese community",
    "official_bbs": "Processing official Community",
    "create": "Establish",
    "cancel": "Cancel",
    "new_project": "Please enter a name for the new project",
    "rename_project": "Please enter the project name to modify",
    "delete": "Delete",
    "config_delete": "Are you sure to delete x?",
    "tip": "Reminder",
    "limit_project_name_length": "The name cannot exceed 24 characters",
    "limit_project_name_exist": "The project already exists. Please re-enter a new project name",
    "please_input_project_name": "Project name cannot be empty",
    "language": "Multilingual",
    "language_setting": "Set language",
    "英语": "English",
    "简体中文": "Simplified Chinese",
    "繁体中文": "Traditional Chinese",
    "日语": "Japanese",
    "西班牙语": "Spanish",
    "法语": "French",
    "德语": "German",
    "意大利语": "Italian",
    "韩语": "Korean",
    "language_desc":
        "If the translation of any content is incorrect or a new language needs to be added, please contact me by email. Thank you very much for your support and understanding!",
    "send": "Send out"
  },
  "zh": {
    "about": "联系我",
    'open_error': '启动失败，请稍后重试',
    "feature": "知识点",
    "search": "速查",
    "search_result_empty": "没有搜索到相关信息，请试试其他关键字",
    "name": "名称",
    "fields": "字段",
    "example": "示例",
    "error_desc": "如果翻译内容不正确或者页面出现异常，请及时联系我，感谢您的支持!",
    "code": "源代码",
    "parameters": "参数",
    "constructors": "构造方法",
    "methods": "成员方法",
    "syntax": "语法",
    "name_function": "函数名",
    "name_class": "类名",
    "description": "描述",
    "code_examples": "代码示例",
    "share": "分享",
    "feedback": "Processing Compiler 相关问题反馈",
    "like_me": "鼓励我一下",
    "ok": "确定",
    "recommend": "推荐朋友",
    "wechat": "微信",
    "rename": "重新命名",
    "more": "更多",
    "email": "邮箱",
    "Processing中文论坛": "Processing中文论坛",
    "about_how": "如何联系到我",
    "light_mode": "浅色模式",
    "dark_mode": "深色模式",
    "system_mode": "跟随系统",
    "reset": "恢复默认模式",
    "theme": "主题风格",
    "setting_code_full_screen": "是否全屏",
    "email_error": "启动邮箱程序失败，请检查是否安装邮箱程序，如有更多问题，请前往应用市场反馈",
    "qq_error": "启动QQ程序失败，请检查是否安装QQ程序，如有更多问题，请前往应用市场反馈",
    "theme_setting": "设置主题风格",
    "app_name": "Processing",
    "create_project": "创建一个新项目",
    "create_processing": "新建Processing项目",
    "create_p5": "新建p5.js项目",
    "create_python": "新建Processing.py项目",
    "editor_setting": "编辑器设置",
    "setting": "设置",
    "show_code_line_number": "显示代码行号",
    "setting_code_font_size": "设置代码字体大小",
    "code_theme": "编辑器风格",
    "empty_pro": "开启您的创意编程吧 !",
    "loading": "加载中 ...",
    "slide_setting_font_size": "滑动手指进行字体大小设置",
    "project": "项目",
    "reference": "参考",
    "createTimeDesc": "创建时间：",
    "china_bbs": "Processing 中文社区",
    "official_bbs": "Processing 官方社区",
    "create": "创建",
    "cancel": "取消",
    "new_project": "请输入新项目的名称",
    "rename_project": "请输入要修改的项目名称",
    "delete": "删除",
    "config_delete": "您确定删除x吗 ？",
    "tip": "温馨提示",
    "limit_project_name_length": "名称不能超过24个字符",
    "limit_project_name_exist": "该项目已经存在，请重新输入新的项目名称",
    "please_input_project_name": "项目名称不能为空",
    "language": "多语言",
    "language_setting": "设置语言",
    "英语": "英语",
    "简体中文": "简体中文",
    "繁体中文": "繁体中文",
    "日语": "日语",
    "西班牙语": "西班牙语",
    "法语": "法语",
    "德语": "德语",
    "意大利语": "意大利语",
    "韩语": "韩语",
    "language_desc": "如果有内容翻译不对或者需要增加新的语言，请发邮件联系我，非常感谢您的支持和理解!",
    "send": "发送"
  },
  "cht": {
    "app_share": "Processing or p5. js or Py by Compiler",
    "about": "聯系我",
    "feature": "知識點",
    "search": "速查",
    "search_result_empty": "沒有蒐索到相關資訊，請試試其他關鍵字",
    "name": "名稱",
    "fields": "欄位",
    "example": "示例",
    "error_desc": "如果翻譯內容不正確或者頁面出現異常，請及時聯系我，感謝您的支持！",
    "code": "原始程式碼",
    "parameters": "參數",
    "constructors": "構造方法",
    "methods": "成員方法",
    "syntax": "語法",
    "name_function": "函數名",
    "name_class": "類名",
    "description": "描述",
    "code_examples": "程式碼示例",
    "share": "分享",
    "feedback": "Processing Compiler相關問題迴響",
    "like_me": "鼓勵我一下",
    "ok": "確定",
    "recommend": "推薦朋友",
    "wechat": "微信",
    "rename": "重新命名",
    "more": "更多",
    "email": "郵箱",
    "Processing中文论坛": "Processing中文論壇",
    "about_how": "如何聯系到我",
    "light_mode": "淺色模式",
    "dark_mode": "深色模式",
    "system_mode": "跟隨系統",
    "reset": "恢復默認模式",
    "theme": "主題風格",
    "email_error": "啟動郵箱程式失敗，請檢查是否安裝郵箱程式，如有更多問題，請前往應用市場迴響",
    "qq_error": "啟動QQ程式失敗，請檢查是否安裝QQ程式，如有更多問題，請前往應用市場迴響",
    "theme_setting": "設定主題風格",
    "app_name": "Processing",
    "create_project": "創建一個新項目",
    "create_processing": "新建Processing項目",
    "create_p5": "新建p5. js項目",
    "create_python": "新建Processing. py項目",
    "editor_setting": "編輯器設定",
    "setting": "設定",
    "show_code_line_number": "顯示程式碼行號",
    "setting_code_font_size": "設定程式碼字體大小",
    "code_theme": "編輯器風格",
    "empty_pro": "開啟您的創意程式設計吧！",
    "loading": "加載中…",
    "slide_setting_font_size": "滑動手指進行字體大小設定",
    "project": "項目",
    "reference": "參攷",
    "createTimeDesc": "創建時間：",
    "china_bbs": "Processing中文社區",
    "official_bbs": "Processing官方社區",
    "create": "創建",
    "cancel": "取消",
    "new_project": "請輸入新項目的名稱",
    "rename_project": "請輸入要修改的項目名稱",
    "delete": "删除",
    "config_delete": "您確定删除x嗎？",
    "tip": "溫馨提示",
    "limit_project_name_length": "名稱不能超過24個字元",
    "limit_project_name_exist": "該項目已經存在，請重新輸入新的項目名稱",
    "please_input_project_name": "項目名稱不能為空",
    "language": "多語言",
    "language_setting": "設定語言",
    "英语": "英語",
    "简体中文": "簡體中文",
    "繁体中文": "繁體中文",
    "日语": "日語",
    "西班牙语": "西班牙語",
    "法语": "法語",
    "德语": "德語",
    "意大利语": "義大利語",
    "韩语": "韓語",
    "language_desc": "如果有內容翻譯不對或者需要新增新的語言，請發郵件聯系我，非常感謝您的支持和理解！",
    "send": "發送"
  },
  "jp": {
    "app_share": "Processing or p5.js or Py by Compiler",
    "about": "連絡して",
    "feature": "インテリジェントポイント",
    "search": "速さで調べる",
    "search_result_empty": "関連情報が検索されませんでした。他のキーワードを試してみてください。",
    "name": "名前",
    "fields": "フィールド",
    "example": "例",
    "error_desc": "翻訳内容が正しくない場合、またはページに異常が発生した場合は、すぐに連絡してください。サポートに感謝します。",
    "code": "ソースコード",
    "parameters": "パラメータ",
    "constructors": "構築方法",
    "methods": "メンバーメソッド",
    "syntax": "構文",
    "name_function": "関数名",
    "name_class": "クラス名",
    "description": "説明",
    "code_examples": "コードの例",
    "share": "分かち合う",
    "feedback": "Processing Compiler関連問題フィードバック",
    "like_me": "励ましてくれ",
    "ok": "を選択します。",
    "recommend": "友人を推薦する",
    "wechat": "微信",
    "rename": "名前を変更",
    "more": "その他",
    "email": "メールボックス",
    "Processing中文论坛": "プロセス中国語フォーラム",
    "about_how": "私に連絡する方法",
    "light_mode": "薄い色のモード",
    "dark_mode": "ダークモード",
    "system_mode": "システムに従う",
    "reset": "デフォルトモードを復元",
    "theme": "テーマスタイル",
    "email_error": "メールボックスプログラムの起動に失敗しました。メールボックスプログラムをインストールするかどうかを確認してください。詳細については、アプリケーション市場のフィードバックに行ってください。",
    "qq_error": "QQプログラムを起動して失敗して、QQプログラムをインストールするかどうかを検査して、更に多くの問題があるならば、アプリケーション市場のフィードバックに行ってください",
    "theme_setting": "テーマスタイルの設定",
    "app_name": "Processing",
    "create_project": "新規プロジェクトの作成",
    "create_processing": "新規プロセスプロジェクト",
    "create_p5": "新しいp 5.jsプロジェクト",
    "create_python": "新規作成pyプロジェクト",
    "editor_setting": "エディタの設定",
    "setting": "設定",
    "show_code_line_number": "コード行番号の表示",
    "setting_code_font_size": "コードフォントサイズの設定",
    "code_theme": "エディタスタイル",
    "empty_pro": "クリエイティブプログラミングを開始しましょう。",
    "loading": "ロード中...",
    "slide_setting_font_size": "指をスライドしてフォントサイズを設定",
    "project": "プロジェクト",
    "reference": "リファレンス",
    "createTimeDesc": "作成時間:",
    "china_bbs": "プロセス中国語コミュニティ",
    "official_bbs": "プロセス公式コミュニティ",
    "create": "作成",
    "cancel": "キャンセル",
    "new_project": "新しいプロジェクトの名前を入力してください",
    "rename_project": "変更する項目名を入力してください",
    "delete": "削除",
    "config_delete": "本当にxを削除しますか?",
    "tip": "お知らせ",
    "limit_project_name_length": "名前は24文字以内",
    "limit_project_name_exist": "このアイテムは既に存在します。新しいアイテム名を再入力してください。",
    "please_input_project_name": "プロジェクト名を空にすることはできません",
    "language": "多言語",
    "language_setting": "言語の設定",
    "英语": "英語",
    "简体中文": "簡体字中国語",
    "繁体中文": "繁体字中国語",
    "日语": "日本語",
    "西班牙语": "スペイン語",
    "法语": "フランス語",
    "德语": "ドイツ語",
    "意大利语": "イタリア語",
    "韩语": "韓国語",
    "language_desc": "もし内容の翻訳が間違っていたり、新しい言語を追加する必要がある場合は、メールで連絡してください。サポートと理解に感謝します。",
    "send": "送信"
  },
  "spa": {
    "app_share": "Procesamiento o P5. JS o Py by Compiler",
    "about": "Póngase en contacto conmigo.",
    "feature": "Puntos de conocimiento",
    "search": "Examen rápido",
    "search_result_empty": "No se ha encontrado información relevante, pruebe otra palabra clave",
    "name": "Nombre",
    "fields": "Campo",
    "example": "Ejemplo",
    "error_desc": "¡Si el contenido de la traducción no es correcto o la página es anormal, por favor póngase en contacto conmigo a tiempo, gracias por su apoyo!",
    "code": "Código fuente",
    "parameters": "Parámetros",
    "constructors": "Método de construcción",
    "methods": "Método de afiliación",
    "syntax": "Gramática",
    "name_function": "Nombre de la función",
    "name_class": "Nombre de la clase",
    "description": "Descripción",
    "code_examples": "Ejemplo de código",
    "share": "Compartir",
    "feedback": "Retroalimentación de problemas relacionados con el compilador de procesos",
    "like_me": "Anímeme.",
    "ok": "Determinar",
    "recommend": "Recomendar amigos",
    "wechat": "Wechat",
    "rename": "Renombrar",
    "more": "Más",
    "email": "Buzón de correo",
    "Processing中文论坛": "Foro chino de procesamiento",
    "about_how": "Cómo contactarme",
    "light_mode": "Modo de luz",
    "dark_mode": "Modo oscuro",
    "system_mode": "Sistema de seguimiento",
    "reset": "Restaurar el modo predeterminado",
    "theme": "Estilo temático",
    "email_error":
        "Fallo al iniciar el programa de buzón de correo. Compruebe si el programa de buzón de correo está instalado. Para más preguntas, vaya a la aplicación de retroalimentación del mercado",
    "qq_error": "Qq Start Program failed, Please check if the QQ program is installed, if there are more Questions, please go to the Application Market feedback",
    "theme_setting": "Establecer estilo de tema",
    "app_name": "Procesamiento",
    "create_project": "Crear un nuevo proyecto",
    "create_processing": "Nuevo proyecto de procesamiento",
    "create_p5": "Nuevo P5. Proyecto js",
    "create_python": "Nuevo proceso. Proyecto Py",
    "editor_setting": "Configuración del editor",
    "setting": "Configuración",
    "show_code_line_number": "Mostrar números de línea de código",
    "setting_code_font_size": "Establecer el tamaño del tipo de letra del Código",
    "code_theme": "Estilo del editor",
    "empty_pro": "¡Abre tu programación creativa!",
    "loading": "Cargando...",
    "slide_setting_font_size": "Deslizar el dedo para establecer el tamaño de la fuente",
    "project": "Proyecto",
    "reference": "Referencia",
    "createTimeDesc": "Hora de creación:",
    "china_bbs": "Comunidad China de procesamiento",
    "official_bbs": "Comunidad oficial de procesamiento",
    "create": "Crear",
    "cancel": "Cancelar",
    "new_project": "Introduzca el nombre del nuevo proyecto",
    "rename_project": "Introduzca el nombre del proyecto a modificar",
    "delete": "Borrar",
    "config_delete": "¿Estás seguro de que quieres borrar X?",
    "tip": "Consejos cálidos",
    "limit_project_name_length": "El nombre no puede exceder de 24 caracteres",
    "limit_project_name_exist": "El proyecto ya existe. Vuelva a introducir el nuevo nombre del proyecto",
    "please_input_project_name": "El nombre del proyecto no puede estar vacío",
    "language": "Multilingüismo",
    "language_setting": "Establecer idioma",
    "英语": "Inglés",
    "简体中文": "Chino simplificado",
    "繁体中文": "Chino tradicional",
    "日语": "Japonés",
    "西班牙语": "Español",
    "法语": "Francés",
    "德语": "Alemán",
    "意大利语": "Italiano",
    "韩语": "Coreano",
    "language_desc":
        "¡Si el contenido no está traducido correctamente o necesita a ñadir un nuevo idioma, por favor póngase en contacto conmigo por correo electrónico, muchas gracias por su apoyo y comprensión!",
    "send": "Enviar"
  },
  "fra": {
    "app_share": "Traitement ou P5. JS ou Py par compilateur",
    "about": "Contactez - moi.",
    "feature": "Points de connaissance",
    "search": "Vite!",
    "search_result_empty": "Aucune information n'a été trouvée, Veuillez essayer d'autres mots clés",
    "name": "Nom",
    "fields": "Champ",
    "example": "Exemples",
    "error_desc": "Si le contenu de la traduction est incorrect ou si la page est anormale, veuillez me contacter à temps, merci pour votre soutien!",
    "code": "Code source",
    "parameters": "Paramètres",
    "constructors": "Méthode de construction",
    "methods": "Méthode d'adhésion",
    "syntax": "Syntaxe",
    "name_function": "Nom de la fonction",
    "name_class": "Nom de la classe",
    "description": "Description",
    "code_examples": "Exemple de code",
    "share": "Partager",
    "feedback": "Commentaires sur les questions liées au compilateur de processus",
    "like_me": "Encouragez - moi.",
    "ok": "C'est sûr.",
    "recommend": "Recommander des amis",
    "wechat": "Wechat",
    "rename": "Renommer",
    "more": "Plus",
    "email": "E - mail",
    "Processing中文论坛": "Forum chinois de traitement",
    "about_how": "Comment me joindre",
    "light_mode": "Mode lumière",
    "dark_mode": "Mode foncé",
    "system_mode": "Système de suivi",
    "reset": "Restaurer le mode par défaut",
    "theme": "Style thématique",
    "email_error":
        "Impossible de démarrer le programme de boîte aux lettres. Veuillez vérifier si le programme de boîte aux lettres est installé. Si vous avez d'autres problèmes, allez à l'application Market feedback",
    "qq_error":
        "Impossible de démarrer le programme QQ. Veuillez vérifier si le programme QQ est installé. Si vous avez d'autres questions, veuillez vous rendre au marché de l'application pour obtenir des commentaires.",
    "theme_setting": "Définir le style du thème",
    "app_name": "Traitement",
    "create_project": "Créer un nouveau projet",
    "create_processing": "Nouveau projet de traitement",
    "create_p5": "Nouveau P5. Projet JS",
    "create_python": "Nouveau processus. Projet Py",
    "editor_setting": "Paramètres de l'éditeur",
    "setting": "Paramètres",
    "show_code_line_number": "Afficher le numéro de ligne du Code",
    "setting_code_font_size": "Définir la taille de la police de code",
    "code_theme": "Style de l'éditeur",
    "empty_pro": "Commencez votre programmation créative!",
    "loading": "Chargement...",
    "slide_setting_font_size": "Glissez votre doigt pour définir la taille de la police",
    "project": "Projets",
    "reference": "RÉFÉRENCES",
    "createTimeDesc": "Heure de création:",
    "china_bbs": "Processing Chinese community",
    "official_bbs": "Communauté officielle de traitement",
    "create": "Création",
    "cancel": "Annulation",
    "new_project": "Veuillez saisir un nom pour le nouveau projet",
    "rename_project": "Veuillez saisir le nom du projet à modifier",
    "delete": "Supprimer",
    "config_delete": "Êtes - vous sûr de vouloir supprimer X?",
    "tip": "Conseils chaleureux",
    "limit_project_name_length": "Le nom ne peut pas dépasser 24 caractères",
    "limit_project_name_exist": "Le projet existe déjà, veuillez saisir à nouveau le nouveau nom du projet",
    "please_input_project_name": "Le nom du projet ne peut pas être vide",
    "language": "Multilingue",
    "language_setting": "Définir la langue",
    "英语": "Anglais",
    "简体中文": "Chinois simplifié",
    "繁体中文": "Chinois traditionnel",
    "日语": "Japonais",
    "西班牙语": "Espagnol",
    "法语": "Français",
    "德语": "Allemand",
    "意大利语": "Italien",
    "韩语": "Coréen",
    "language_desc":
        "S'il y a des erreurs dans la traduction du contenu ou si vous avez besoin d'ajouter une nouvelle langue, s'il vous plaît envoyez - moi un email et merci beaucoup pour votre soutien et votre compréhension!",
    "send": "Envoyer"
  },
  "de": {
    "app_share": "Verarbeitung oder p5. js oder Py by Compiler",
    "about": "Kontaktieren Sie mich",
    "feature": "Knowledge Points",
    "search": "Schnelle Überprüfung",
    "search_result_empty": "Es wurden keine relevanten Informationen gefunden.",
    "name": "Name",
    "fields": "Feld",
    "example": "Beispiel",
    "error_desc": "Wenn der Übersetzungsinhalt falsch ist oder die Seite abnormal ist, kontaktieren Sie mich bitte rechtzeitig. Vielen Dank für Ihre Unterstützung!",
    "code": "Quellcode (Quelle)",
    "parameters": "Parameter",
    "constructors": "Methode der Konstruktion",
    "methods": "Verfahren der Mitgliedstaaten",
    "syntax": "Grammatik",
    "name_function": "Name der Funktion",
    "name_class": "Name der Klasse",
    "description": "Beschreibung",
    "code_examples": "Beispiel des Codes",
    "share": "Aktie",
    "feedback": "Feedback zu relevanten Problemen des Compilers",
    "like_me": "Ermutige mich",
    "ok": "Bestimmen",
    "recommend": "Empfohlene Freunde",
    "wechat": "WeChatGenericName",
    "rename": "Umbenennen",
    "more": "Mehr",
    "email": "Briefkasten",
    "Processing中文论坛": "Processing Chinese Forum",
    "about_how": "Wie kann ich kontaktiert werden",
    "light_mode": "Modus des Lichts",
    "dark_mode": "Dunkler Modus",
    "system_mode": "Folgen des Systems",
    "reset": "Standardmodus wiederherstellen",
    "theme": "Stil des Designs",
    "email_error":
        "Das Mailbox-Programm konnte nicht gestartet werden. Bitte überprüfen Sie, ob das Mailbox-Programm installiert ist. Wenn Sie weitere Fragen haben, wenden Sie sich bitte an den Application Market, um Feedback zu erhalten.",
    "qq_error":
        "Das QQ-Programm konnte nicht gestartet werden. Bitte überprüfen Sie, ob das QQ-Programm installiert ist. Wenn Sie weitere Fragen haben, gehen Sie bitte zum Anwendungsmarkt, um Feedback zu erhalten.",
    "theme_setting": "Stil festlegen",
    "app_name": "Verarbeitung",
    "create_project": "Neues Projekt erstellen",
    "create_processing": "Neues Verarbeitungsprojekt",
    "create_p5": "Neuer P5 Projekt JS",
    "create_python": "Neue Bearbeitung erstellen Projekt Py",
    "editor_setting": "Einstellungen des Editors",
    "setting": "Zur Einrichtung",
    "show_code_line_number": "Code-Zeilennummer anzeigen",
    "setting_code_font_size": "Schriftgröße festlegen",
    "code_theme": "Stil des Editors",
    "empty_pro": "Starten Sie Ihre kreative Programmierung!",
    "loading": "Laden",
    "slide_setting_font_size": "Schieben Sie Ihren Finger, um die Schriftgröße einzustellen",
    "project": "Projekt",
    "reference": "Referenzressourcen (Referenzressourcen)",
    "createTimeDesc": "Erstellt auf:",
    "china_bbs": "Verarbeitung der chinesischen Gemeinschaft",
    "official_bbs": "Verarbeitende amtliche Gemeinschaft",
    "create": "Stellen",
    "cancel": "Stornieren",
    "new_project": "Bitte geben Sie einen Namen für das neue Projekt ein",
    "rename_project": "Bitte geben Sie den Projektnamen ein, um ihn zu ändern",
    "delete": "Löschen",
    "config_delete": "Sind Sie sicher, x zu löschen?",
    "tip": "Erinnerung",
    "limit_project_name_length": "Der Name darf 24 Zeichen nicht überschreiten",
    "limit_project_name_exist": "Das Projekt existiert bereits. Bitte geben Sie einen neuen Projektnamen ein",
    "please_input_project_name": "Projektname kann nicht leer sein",
    "language": "Mehrsprachigkeit",
    "language_setting": "Sprache festlegen",
    "英语": "Englisch",
    "简体中文": "Vereinfachtes Chinesisch",
    "繁体中文": "Traditionelles Chinesisch",
    "日语": "Japanisch",
    "西班牙语": "Spanisch",
    "法语": "Französisch",
    "德语": "Deutsch",
    "意大利语": "Italienisch",
    "韩语": "Koreanisch",
    "language_desc":
        "Wenn die Übersetzung von Inhalten falsch ist oder eine neue Sprache hinzugefügt werden muss, kontaktieren Sie mich bitte per E-Mail. Vielen Dank für Ihre Unterstützung und Verständnis!",
    "send": "Senden Sie"
  },
  "it": {
    "app_share": "Elaborazione o p5. js o Py by Compiler",
    "about": "Contattami",
    "feature": "Punti di conoscenza",
    "search": "Controllo rapido",
    "search_result_empty": "Non sono state trovate informazioni rilevanti. Si prega di provare altre parole chiave",
    "name": "Nome",
    "fields": "Campo",
    "example": "Esempio",
    "error_desc": "Se il contenuto di traduzione non è corretto o la pagina è anormale, si prega di contattarmi in tempo. Grazie per il vostro supporto!",
    "code": "Codice sorgente",
    "parameters": "Parametro",
    "constructors": "Metodo di costruzione",
    "methods": "Metodo degli Stati membri",
    "syntax": "Grammatica",
    "name_function": "Nome della funzione",
    "name_class": "Nome della classe",
    "description": "Descrivere",
    "code_examples": "Esempio di codice",
    "share": "Condivisione",
    "feedback": "Feedback sui problemi rilevanti del compilatore di elaborazione",
    "like_me": "Incoraggiare me",
    "ok": "Determinare",
    "recommend": "Raccomando amici",
    "wechat": "Chat",
    "rename": "Rinomina",
    "more": "Più",
    "email": "Mailbox",
    "Processing中文论坛": "Forum cinese di trasformazione",
    "about_how": "Come posso essere contattato",
    "light_mode": "Modalità della luce",
    "dark_mode": "Modalità oscura",
    "system_mode": "Sistema di monitoraggio",
    "reset": "Ripristina la modalità predefinita",
    "theme": "Stile di tema",
    "email_error":
        "Impossibile avviare il programma delle caselle postali. Controlla se il programma delle caselle postali è installato. Se hai altre domande, vai al mercato delle applicazioni per il feedback",
    "qq_error": "Impossibile avviare il programma QQ. Controlla se il programma QQ è installato. Se hai altre domande, vai al mercato applicativo per il feedback",
    "theme_setting": "Imposta stile di tema",
    "app_name": "Elaborazione",
    "create_project": "Creare un nuovo progetto",
    "create_processing": "Nuovo progetto di elaborazione",
    "create_p5": "Nuovo P5 Progetto JS",
    "create_python": "Crea un nuovo trattamento Progetto Py",
    "editor_setting": "Impostazioni dell'editor",
    "setting": "Montato",
    "show_code_line_number": "Mostra numero di linea di codice",
    "setting_code_font_size": "Imposta dimensione del font codice",
    "code_theme": "Editor stile",
    "empty_pro": "Iniziate la vostra programmazione creativa!",
    "loading": "Caricamento",
    "slide_setting_font_size": "Far scorrere il dito per impostare la dimensione del carattere",
    "project": "Progetto",
    "reference": "Risorse di riferimento",
    "createTimeDesc": "Creato su:",
    "china_bbs": "Elaborazione della comunità cinese",
    "official_bbs": "Comunità di trasformazione",
    "create": "Stabilire",
    "cancel": "Annulla",
    "new_project": "Inserisci un nome per il nuovo progetto",
    "rename_project": "Inserisci il nome del progetto per modificare",
    "delete": "Eliminare",
    "config_delete": "Sei sicuro di cancellare x?",
    "tip": "Promemoria",
    "limit_project_name_length": "Il nome non può superare i caratteri 24",
    "limit_project_name_exist": "Il progetto esiste già. Inserisci un nuovo nome del progetto",
    "please_input_project_name": "Il nome del progetto non può essere vuoto",
    "language": "Multilingue",
    "language_setting": "Imposta la lingua",
    "英语": "Inglese",
    "简体中文": "Semplificato cinese",
    "繁体中文": "Cinese tradizionale",
    "日语": "Giapponese",
    "西班牙语": "Spagnolo",
    "法语": "Francese",
    "德语": "Tedesco",
    "意大利语": "Italiano",
    "韩语": "Coreano",
    "language_desc":
        "Se la traduzione di qualsiasi contenuto è errata o deve essere aggiunta una nuova lingua, per favore contattatemi via e-mail. Grazie mille per il vostro supporto e comprensione!",
    "send": "Inviare fuori"
  },
  "kor": {
    "app_share": "Processing or p5.js or Py by Compiler",
    "about": "연락 주세요.",
    "feature": "지식점",
    "search": "속사",
    "search_result_empty": "관련 정보가 검색되지 않았습니다. 다른 키워드를 시도해 보십시오",
    "name": "이름:",
    "fields": "필드",
    "example": "예제",
    "error_desc": "만약 번역 내용이 정확하지 않거나 페이지에 이상이 발생하면 즉시 저에게 연락을 주십시오. 당신의 지지에 감사 드립니다!",
    "code": "소스 코드",
    "parameters": "매개 변수",
    "constructors": "구조 방법",
    "methods": "구성원 메서드",
    "syntax": "구문",
    "name_function": "함수명",
    "name_class": "클래스 이름",
    "description": "묘사",
    "code_examples": "코드 예",
    "share": "나누다",
    "feedback": "Processing Compiler 관련 질문 피드백",
    "like_me": "격려해 주세요.",
    "ok": "확정하다",
    "recommend": "친구 추천",
    "wechat": "위챗",
    "rename": "다시 명명한다",
    "more": "더.",
    "email": "우편함",
    "Processing中文论坛": "Processing 중국어 포럼",
    "about_how": "어떻게 나에게 연락합니까",
    "light_mode": "연한 색 모드",
    "dark_mode": "짙은 색 모드",
    "system_mode": "시스템 따라가기",
    "reset": "기본 모드 복원",
    "theme": "주제 스타일",
    "email_error": "메일박스 프로그램을 시작하는 데 실패했습니다. 메일박스 프로그램을 설치했는지 확인하십시오. 더 많은 문제가 있으면 응용 시장에 가서 피드백을 주십시오",
    "qq_error": "QQ 프로그램을 시작하는 데 실패했습니다. QQ 프로그램을 설치하는지 확인하세요. 더 많은 문제가 있으면 앱 시장에 가서 피드백을 하세요.",
    "theme_setting": "테마 스타일 설정",
    "app_name": "Processing",
    "create_project": "새 항목 만들기",
    "create_processing": "새 Processing 프로젝트",
    "create_p5": "새 p5.js 프로젝트",
    "create_python": "새 Processing.py 프로젝트",
    "editor_setting": "편집기 설정",
    "setting": "설정",
    "show_code_line_number": "코드 행 번호 표시",
    "setting_code_font_size": "코드 글꼴 크기 설정",
    "code_theme": "편집기 스타일",
    "empty_pro": "당신의 창의적인 프로그래밍을 시작합시다!",
    "loading": "로드 중...",
    "slide_setting_font_size": "손가락 슬라이딩 글꼴 크기 설정",
    "project": "항목",
    "reference": "참고 자료",
    "createTimeDesc": "만든 날짜:",
    "china_bbs": "Processing 중국어 커뮤니티",
    "official_bbs": "Processing 공식 커뮤니티",
    "create": "창설",
    "cancel": "취소",
    "new_project": "새 항목의 이름을 입력하십시오",
    "rename_project": "수정할 항목 이름을 입력하십시오.",
    "delete": "삭제",
    "config_delete": "X를 삭제하시겠습니까?",
    "tip": "따뜻한 힌트",
    "limit_project_name_length": "이름은 24자를 초과할 수 없습니다.",
    "limit_project_name_exist": "항목이 이미 존재합니다. 새 항목 이름을 다시 입력하십시오.",
    "please_input_project_name": "항목 이름은 비워둘 수 없습니다.",
    "language": "다국어",
    "language_setting": "언어 설정",
    "英语": "영어.",
    "简体中文": "중국어 간체",
    "繁体中文": "중국어 번체",
    "日语": "일본어",
    "西班牙语": "스페인어",
    "法语": "프랑스어",
    "德语": "독일어",
    "意大利语": "이탈리아어",
    "韩语": "한국어 공부 해요.",
    "language_desc": "만약 내용 번역이 잘못되거나 새로운 언어를 추가해야 한다면 메일로 저에게 연락을 주십시오. 당신의 지지와 이해에 매우 감사합니다!",
    "send": "보내다"
  }
};
